export { EditIcon } from "./edit-icon"
export { DeleteIcon } from "./delete-icon"
export { ViewIcon } from "./view-icon"
export { HomeIcon } from "./home-icon"
export { ArchiveIcon } from "./archive-icon"
export { MessageIcon } from "./message-icon"
export { DownloadIcon } from "./download-icon"
export { ReportsIcon } from "./reports-icon"
export { SearchIcon } from "./search-icon"
export { CartIcon } from "./cart-icon"
export { WalletIcon } from "./wallet-icon"
export { StoreIcon } from "./store-icon"
export { ClientsIcon } from "./clients-icon"
export { CogIcon } from "./cog-icon"
export { SunIcon } from "./sun-icon"
export { MoonIcon } from "./moon-icon"
export { BulkUploadIcon } from "./bulk-upload-icon"
export { CSVIcon } from "./csv-icon"
export { CoinsIcon } from "./coins-icon"
export { DayCloudyIcon } from "./day-cloudy-icon"
export {VodacomIcon} from "./vodacom"
export {AirtelIcon} from "./airtel"
export {YasIcon} from "./mixx-by-yas"