CREATE TABLE "locations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"region" text NOT NULL,
	"district" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "locations_region_district_unique" ON "locations" USING btree ("region","district");
--> statement-breakpoint
CREATE INDEX "locations_region_idx" ON "locations" USING btree ("region");
--> statement-breakpoint
INSERT INTO "locations" ("region", "district") VALUES
  ('Arusha','Meru'),
  ('Arusha','Arusha City'),
  ('Arusha','Arusha'),
  ('Arusha','Karatu'),
  ('Arusha','Longido'),
  ('Arusha','Monduli'),
  ('Arusha','Ngorongoro'),
  ('Dar es Salaam','Ilala'),
  ('Dar es Salaam','Kinondoni'),
  ('Dar es Salaam','Temeke'),
  ('Dar es Salaam','Kigamboni'),
  ('Dar es Salaam','Ubungo'),
  ('Dodoma','Bahi'),
  ('Dodoma','Chamwino'),
  ('Dodoma','Chemba'),
  ('Dodoma','Dodoma'),
  ('Dodoma','Kondoa'),
  ('Dodoma','Kongwa'),
  ('Dodoma','Mpwapwa'),
  ('Geita','Bukombe'),
  ('Geita','Chato'),
  ('Geita','Geita Town'),
  ('Geita','Mbogwe'),
  ('Geita','Nyang’hwale'),
  ('Iringa','Iringa'),
  ('Iringa','Kilolo'),
  ('Iringa','Mafinga Town'),
  ('Iringa','Mufindi'),
  ('Kagera','Biharamulo'),
  ('Kagera','Bukoba'),
  ('Kagera','Karagwe'),
  ('Kagera','Kyerwa'),
  ('Kagera','Missenyi'),
  ('Kagera','Muleba'),
  ('Kagera','Ngara'),
  ('Katavi','Mlele'),
  ('Katavi','Mpanda'),
  ('Katavi','Mpanda Town'),
  ('Kigoma','Buhigwe'),
  ('Kigoma','Kakonko'),
  ('Kigoma','Kasulu'),
  ('Kigoma','Kasulu Town'),
  ('Kigoma','Kibondo'),
  ('Kigoma','Kigoma'),
  ('Kigoma','Kigoma-Ujiji'),
  ('Kigoma','Uvinza'),
  ('Kilimanjaro','Hai'),
  ('Kilimanjaro','Moshi'),
  ('Kilimanjaro','Mwanga'),
  ('Kilimanjaro','Rombo'),
  ('Kilimanjaro','Same'),
  ('Kilimanjaro','Siha'),
  ('Kusini Pemba','Chake Chake'),
  ('Kusini Pemba','Mkoani'),
  ('Kusini Unguja','Kati'),
  ('Kusini Unguja','Kusini'),
  ('Lindi','Kilwa'),
  ('Lindi','Lindi'),
  ('Lindi','Liwale'),
  ('Lindi','Nachingwea'),
  ('Lindi','Ruangwa'),
  ('Manyara','Babati Town'),
  ('Manyara','Babati'),
  ('Manyara','Hanang'),
  ('Manyara','Kiteto'),
  ('Manyara','Mbulu'),
  ('Manyara','Simanjiro'),
  ('Mara','Bunda'),
  ('Mara','Butiama'),
  ('Mara','Musoma'),
  ('Mara','Rorya'),
  ('Mara','Serengeti'),
  ('Mara','Tarime'),
  ('Mbeya','Busokelo'),
  ('Mbeya','Chunya'),
  ('Mbeya','Kyela'),
  ('Mbeya','Mbarali'),
  ('Mbeya','Mbeya City'),
  ('Mbeya','Mbeya'),
  ('Mbeya','Rungwe'),
  ('Mjini Magharibi Zanzibar','Magharibi'),
  ('Mjini Magharibi Zanzibar','Mjini'),
  ('Morogoro','Gairo'),
  ('Morogoro','Kilombero'),
  ('Morogoro','Kilosa'),
  ('Morogoro','Morogoro'),
  ('Morogoro','Mvomero'),
  ('Morogoro','Ulanga'),
  ('Morogoro','Malinyi'),
  ('Morogoro','Ifakara Township'),
  ('Mtwara','Masasi'),
  ('Mtwara','Masasi Town'),
  ('Mtwara','Mtwara'),
  ('Mtwara','Nanyumbu'),
  ('Mtwara','Newala'),
  ('Mtwara','Tandahimba'),
  ('Mwanza','Ilemela'),
  ('Mwanza','Kwimba'),
  ('Mwanza','Magu'),
  ('Mwanza','Misungwi'),
  ('Mwanza','Nyamagana'),
  ('Mwanza','Sengerema'),
  ('Mwanza','Ukerewe'),
  ('Njombe','Ludewa'),
  ('Njombe','Makambako Town'),
  ('Njombe','Makete'),
  ('Njombe','Njombe'),
  ('Njombe','Njombe Town'),
  ('Njombe','Wanging’ombe'),
  ('Pwani','Bagamoyo'),
  ('Pwani','Kibaha'),
  ('Pwani','Kibaha Town'),
  ('Pwani','Kisarawe'),
  ('Pwani','Mafia'),
  ('Pwani','Mkuranga'),
  ('Pwani','Rufiji'),
  ('Rukwa','Kalambo'),
  ('Rukwa','Nkasi'),
  ('Rukwa','Sumbawanga'),
  ('Ruvuma','Mbinga'),
  ('Ruvuma','Songea'),
  ('Ruvuma','Tunduru'),
  ('Ruvuma','Namtumbo'),
  ('Ruvuma','Nyasa'),
  ('Shinyanga','Kahama Town'),
  ('Shinyanga','Kahama'),
  ('Shinyanga','Kishapu'),
  ('Shinyanga','Shinyanga'),
  ('Simiyu','Bariadi'),
  ('Simiyu','Busega'),
  ('Simiyu','Itilima'),
  ('Simiyu','Maswa'),
  ('Simiyu','Meatu'),
  ('Singida','Ikungi'),
  ('Singida','Iramba'),
  ('Singida','Manyoni'),
  ('Singida','Mkalama'),
  ('Singida','Singida'),
  ('Songwe','Ileje'),
  ('Songwe','Mbozi'),
  ('Songwe','Momba'),
  ('Songwe','Songwe'),
  ('Tabora','Igunga'),
  ('Tabora','Kaliua'),
  ('Tabora','Nzega'),
  ('Tabora','Sikonge'),
  ('Tabora','Tabora'),
  ('Tabora','Urambo'),
  ('Tabora','Uyui'),
  ('Tanga','Handeni'),
  ('Tanga','Handeni Town'),
  ('Tanga','Kilindi'),
  ('Tanga','Korogwe Town'),
  ('Tanga','Korogwe'),
  ('Tanga','Lushoto'),
  ('Tanga','Muheza'),
  ('Tanga','Mkinga'),
  ('Tanga','Pangani'),
  ('Tanga','Tanga City')
ON CONFLICT ("region", "district") DO NOTHING;
