/**
 * Tenant Database Schema
 * Each tenant gets their own Neon project with this schema
 */

import { varchar, uuid, pgTable, pgEnum, date, timestamp, text, smallint, numeric, boolean } from 'drizzle-orm/pg-core';

export const APPROVAL_STATUS_ENUM = pgEnum('approval_status', ['APPROVED', 'REJECTED', 'PENDING']);
export const GENDER_ENUM = pgEnum('gender', ['MALE', 'FEMALE']);
export const ID_TYPE_ENUM = pgEnum('id_type', ['NATIONAL_ID', 'PASSPORT', 'DRIVER_LICENSE', 'VOTER_ID']);
export const RELATIONSHIP_ENUM = pgEnum('relationship', ['PARENT', 'SIBLING', 'SPOUSE', 'FRIEND', 'OTHER']);
export const CONTACT_TYPE = pgEnum('contact_type', ['CLIENT', 'LAND_SELLER', 'AUDITOR', 'ICT SUPPORT', 'STATIONERY', 'SURVEYOR'])
export const REGIONS_ENUM = pgEnum('regions', [
    'Arusha',
    'Dar es Salaam',
    'Dodoma',
    'Geita',
    'Iringa',
    'Kagera',
    'Katavi',
    'Kigoma',
    'Kilimanjaro',
    'Kusini Pemba',
    'Kusini Unguja',
    'Lindi',
    'Manyara',
    'Mara',
    'Mbeya',
    'Mjini Magharibi Zanzibar',
    'Morogoro',
    'Mwanza',
    'Njombe',
    'Pwani',
    'Rukwa',
    'Ruvuma',
    'Shinyanga',
    'Simiyu',
    'Singida',
    'Songwe',
    'Tabora',
    'Tanga'
])
export const DISTRICT_ENUM = pgEnum('districts', [
    'Meru',
    'Arusha City',
    'Arusha',
    'Karatu',
    'Longido',
    'Monduli',
    'Ngorongoro',
    'Ilala',
    'Kinondoni',
    'Temeke',
    'Kigamboni',
    'Ubungo',
    'Bahi',
    'Chamwino',
    'Chemba',
    'Dodoma',
    'Kondoa',
    'Kongwa',
    'Mpwapwa',
    'Bukombe',
    'Chato',
    'Geita Town',
    'Mbogwe',
    'Nyang’hwale',
    'Iringa',
    'Kilolo',
    'Mafinga Town',
    'Mufindi',
    'Biharamulo',
    'Bukoba',
    'Karagwe',
    'Kyerwa',
    'Missenyi',
    'Muleba',
    'Ngara',
    'Mlele',
    'Mpanda',
    'Mpanda Town',
    'Buhigwe',
    'Kakonko',
    'Kasulu',
    'Kasulu Town',
    'Kibondo',
    'Kigoma',
    'Kigoma-Ujiji',
    'Uvinza',
    'Hai',
    'Moshi',
    'Mwanga',
    'Rombo',
    'Same',
    'Siha',
    'Chake Chake',
    'Mkoani',
    'Kati',
    'Kusini',
    'Kilwa',
    'Lindi',
    'Liwale',
    'Nachingwea',
    'Ruangwa',
    'Babati Town',
    'Babati',
    'Hanang',
    'Kiteto',
    'Mbulu',
    'Simanjiro',
    'Bunda',
    'Butiama',
    'Musoma',
    'Rorya',
    'Serengeti',
    'Tarime',
    'Busokelo',
    'Chunya',
    'Kyela',
    'Mbarali',
    'Mbeya City',
    'Mbeya',
    'Rungwe',
    'Magharibi',
    'Mjini',
    'Gairo',
    'Kilombero',
    'Kilosa',
    'Morogoro',
    'Mvomero',
    'Ulanga',
    'Malinyi',
    'Ifakara Township',
    'Masasi',
    'Masasi Town',
    'Mtwara',
    'Nanyumbu',
    'Newala',
    'Tandahimba',
    'Ilemela',
    'Kwimba',
    'Magu',
    'Misungwi',
    'Nyamagana',
    'Sengerema',
    'Ukerewe',
    'Ludewa',
    'Makambako Town',
    'Makete',
    'Njombe',
    'Njombe Town',
    'Wanging’ombe',
    'Bagamoyo',
    'Kibaha',
    'Kibaha Town',
    'Kisarawe',
    'Mafia',
    'Mkuranga',
    'Rufiji',
    'Kalambo',
    'Nkasi',
    'Sumbawanga',
    'Mbinga',
    'Songea',
    'Tunduru',
    'Namtumbo',
    'Nyasa',
    'Kahama Town',
    'Kahama',
    'Kishapu',
    'Shinyanga',
    'Bariadi',
    'Busega',
    'Itilima',
    'Maswa',
    'Meatu',
    'Ikungi',
    'Iramba',
    'Manyoni',
    'Mkalama',
    'Singida',
    'Ileje',
    'Mbozi',
    'Momba',
    'Songwe',
    'Igunga',
    'Kaliua',
    'Nzega',
    'Sikonge',
    'Tabora',
    'Urambo',
    'Uyui',
    'Handeni',
    'Handeni Town',
    'Kilindi',
    'Korogwe Town',
    'Korogwe',
    'Lushoto',
    'Muheza',
    'Mkinga',
    'Pangani',
    'Tanga City'
]);

export const contacts = pgTable('contacts', {
    id: uuid('id').primaryKey().defaultRandom(),
    fullName: text('full_name'),
    mobileNumber: text('mobile_number'),
    altMobileNumber: text('alt_mobile_number'),
    email: text('email'),
    gender: GENDER_ENUM('gender'),
    contactType: CONTACT_TYPE('contact_type').default('CLIENT'),
    idType: ID_TYPE_ENUM('id_type'),
    idNumber: text('id_number'),
    region: REGIONS_ENUM('regions'),
    district: DISTRICT_ENUM('district'),
    ward: text('ward'),
    street: text('street'),
    firstNOKName: text('first_NOK_Name'),
    firstNOKMobile: text('first_NOK_Mobile'),
    firstNOKRelationship: RELATIONSHIP_ENUM('first_NOK_Relationship'),
    secondNOKName: text('second_NOK_Name'),
    secondNOKMobile: text('second_NOK_Mobile'),
    secondNOKRelationship: RELATIONSHIP_ENUM('second_NOK_Relationship'),
    clientPhoto: text('clientPhoto').unique(),
    addedBy: text('added_by'),
    isDeleted: boolean('is_deleted').default(false).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const projects = pgTable('projects', {
    id: uuid('id').primaryKey().defaultRandom(),
    projectName: text('project_name').notNull(),
    projectDetails: text('project_details'),
    acquisitionDate: date('acquisition_date'),
    sqmBought: numeric('sqm_bought'),
    acquisitionValue: numeric('acquisition_value').notNull(),
    region: text('region'),
    district: text('district'),
    ward: text('ward').default(''),
    projectOwner: text('project_owner'),
    committmentAmount: numeric('committment_amount'),
    lgaFee: numeric('lga_fee'),
    street: text('street'),
    tpNumber: text('tp_number'),
    tpStatus: text('tp_status'),
    surveyStatus: text('survey_status'),
    surveyNumber: text('survey_number'),
    originalContractPdf: text('original_contract_pdf'),
    supplierName: uuid('supplier_name'),
    mwenyekitiName: text('mwenyekiti_name'),
    mwenyekitiMobile: text('mwenyekiti_mobile'),
    mtendajiName: text('mtendaji_name'),
    mtendajiMobile: text('mtendaji_mobile'),
    numberOfPlots: numeric('number_of_plots'),
    tpUrl: text('tp_url'),
    surveyUrl: text('survey_url'),
    addedBy: text('added_by'),
    isDeleted: boolean('is_deleted').default(false).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
})

// Type exports
export type Contact = typeof contacts.$inferSelect;
export type NewContact = typeof contacts.$inferInsert;
export type Project = typeof projects.$inferSelect;
export type NewProject = typeof projects.$inferInsert;