import { drizzle } from 'drizzle-orm/neon-http';
import { neon } from '@neondatabase/serverless';
import { migrate } from 'drizzle-orm/neon-http/migrator';
import * as schema from '@/database/tenant-schema';

/**
 * Set up a new tenant database with schema and migrations
 */
export async function setupTenantSchema(connectionString: string) {
    console.log('🔧 Setting up tenant schema...');

    try {
        const sql = neon(connectionString);
        const db = drizzle(sql, { schema });

        // Run tenant migrations generated by drizzle.tenants.config.ts
        await migrate(db, { migrationsFolder: './migrations-tenants' });

        console.log('✅ Tenant schema setup completed');

        return db;
    } catch (error) {
        console.error('❌ Error setting up tenant schema:', error);
        throw error;
    }
}

/**
 * Verify tenant database connection
 */
export async function verifyTenantConnection(connectionString: string): Promise<boolean> {
    try {
        const sql = neon(connectionString);
        const db = drizzle(sql);

        // Simple query to test connection
        await sql`SELECT 1`;

        return true;
    } catch (error) {
        console.error('Connection verification failed:', error);
        return false;
    }
}